In [2]:
import pandas as pd
import numpy as np

In [3]:
# Criando um dicionario para ser adicionado em um dataframe
dados = {
    'NomeVendedor': ['Carlos', 'Julia', 'Lucas', 'Fernanda', 'Roberto', 'Camila', 'Ricardo', 'Beatriz', 'Renato', 'Patricia'],
    'QuantidadeVendas': [33, 27, 41, 22, 35, 30, 45, 25, 40, 28],
    'Localidade': ['Sul', 'Nordeste', 'Nordeste', 'Norte', 'Sudeste', 'Sudeste', 'Sudeste','Sul', 'Nordeste','Centro-Oeste']
}
#Criando um DataFrame
df = pd.DataFrame(dados)
print(df)

  NomeVendedor  QuantidadeVendas    Localidade
0       Carlos                33           Sul
1        Julia                27      Nordeste
2        Lucas                41      Nordeste
3     Fernanda                22         Norte
4      Roberto                35       Sudeste
5       Camila                30       Sudeste
6      Ricardo                45       Sudeste
7      Beatriz                25           Sul
8       Renato                40      Nordeste
9     Patricia                28  Centro-Oeste

Agrupamento com metodo min()

In [ ]:
# Buscando menores vendas e vendedores por localidade
# O proprio pandas ja identifica o campo numerico do dataframe
df.groupby("Localidade").min()

             NomeVendedor  QuantidadeVendas
Localidade
Centro-Oeste     Patricia                28
Nordeste            Julia                27
Norte            Fernanda                22
Sudeste            Camila                30
Sul               Beatriz                25

In [ ]:
# Ordenando o campo QuantidadeVendas de forma crescente
df.groupby("Localidade").min().sort_values(by='QuantidadeVendas', ascending=True)

             NomeVendedor  QuantidadeVendas
Localidade
Norte            Fernanda                22
Sul               Beatriz                25
Nordeste            Julia                27
Centro-Oeste     Patricia                28
Sudeste            Camila                30