




## Operações Matemáticas ##

___

### Gerando DataFrames dados para os exemplos

DataFrames- Criando estrutura de dataframes para usar os métodos que apenderemos

In [1]:
import pandas as pd
import numpy as np

# Criando um novo dicionário para ser adicionado em um DataFrame
dados = {
    'NomeVendedor': ['Carlos', 'Julia', 'Lucas', 'Fernanda', 'Roberto', 'Camila', 'Ricardo', 'Beatriz', 'Renato', 'Patricia'],
    'QuantidadeVendas': [33, 27, 41, 22, 33, 30, 45, 25, 40, 28],
    'ValorVendido': [156.45, 123.76, 187.45, 34.21, 12, 543, 512, 587, 10, 234],
    'Localidade': ['Sul', 'Nordeste', 'Nordeste', 'Norte', 'Sudeste', 'Sudeste', 'Sudeste', 'Sul', 'Nordeste', 'Centro-Oeste']
}


# Criando novos DataFrames
df = pd.DataFrame(dados)
df

  NomeVendedor  QuantidadeVendas  ValorVendido    Localidade
0       Carlos                33        156.45           Sul
1        Julia                27        123.76      Nordeste
2        Lucas                41        187.45      Nordeste
3     Fernanda                22         34.21         Norte
4      Roberto                33         12.00       Sudeste
5       Camila                30        543.00       Sudeste
6      Ricardo                45        512.00       Sudeste
7      Beatriz                25        587.00           Sul
8       Renato                40         10.00      Nordeste
9     Patricia                28        234.00  Centro-Oeste

Aplicando funções matemáticas em DataFrames

In [2]:
# Criando uma função para muitiplicar o valor vendido por 5%
def comissao(ValorVendido):
    return ValorVendido * 1.05
# Aplicando a função de comissão a coluna 'ValorVendido' 
df['ValorVendido'].apply(comissao)
# .apply() aplica uma função a cada elemento de uma série ou DataFrame

# Adicionando a coluna 'Comissao' ao DataFrame baseada na coluna 'ValorVendido'
# Aplicando a função de comissão na nova coluna 'Comissao'
df['Comissao'] = df['ValorVendido'].apply(comissao)
df

  NomeVendedor  QuantidadeVendas  ValorVendido    Localidade  Comissao
0       Carlos                33        156.45           Sul  164.2725
1        Julia                27        123.76      Nordeste  129.9480
2        Lucas                41        187.45      Nordeste  196.8225
3     Fernanda                22         34.21         Norte   35.9205
4      Roberto                33         12.00       Sudeste   12.6000
5       Camila                30        543.00       Sudeste  570.1500
6      Ricardo                45        512.00       Sudeste  537.6000
7      Beatriz                25        587.00           Sul  616.3500
8       Renato                40         10.00      Nordeste   10.5000
9     Patricia                28        234.00  Centro-Oeste  245.7000