# Metodo.map()

In [1]:
import pandas as pd
import numpy as np

# Criando um novo dicionário para ser adicionado em um DataFrame
dados = {
    'NomeVendedor': ['Carlos', 'Julia', 'Lucas', 'Fernanda', 'Roberto', 'Camila', 'Ricardo', 'Beatriz', 'Renato', 'Patricia'],
    'QuantidadeVendas': [33, 27, 41, 22, 33, 30, 45, 25, 40, 28],
    'ValorVendido': [156.45, 123.76, 187.45, 34.21, 12, 543, 512, 587, 10, 234],
    'Localidade': ['Sul', 'Nordeste', 'Nordeste', 'Norte', 'Sudeste', 'Sudeste', 'Sudeste', 'Sul', 'Nordeste', 'Centro-Oeste']
}


# Criando novos DataFrames
df = pd.DataFrame(dados)
df

  NomeVendedor  QuantidadeVendas  ValorVendido    Localidade
0       Carlos                33        156.45           Sul
1        Julia                27        123.76      Nordeste
2        Lucas                41        187.45      Nordeste
3     Fernanda                22         34.21         Norte
4      Roberto                33         12.00       Sudeste
5       Camila                30        543.00       Sudeste
6      Ricardo                45        512.00       Sudeste
7      Beatriz                25        587.00           Sul
8       Renato                40         10.00      Nordeste
9     Patricia                28        234.00  Centro-Oeste

In [2]:
dict_mapeamento = {
    "Sul": "Região Sul",
    "Nordeste": "Região Nordeste",
    "Norte": "Região Norte",
    "Sudeste": "Região Sudeste",
    "Centro-Oeste": "Região Centro-Oeste"
}
# Mapeando as strings da coluna 'Localidade' usando o dicionário
df['Localidade'] = df['Localidade'].map(dict_mapeamento)
df

  NomeVendedor  QuantidadeVendas  ValorVendido           Localidade
0       Carlos                33        156.45           Região Sul
1        Julia                27        123.76      Região Nordeste
2        Lucas                41        187.45      Região Nordeste
3     Fernanda                22         34.21         Região Norte
4      Roberto                33         12.00       Região Sudeste
5       Camila                30        543.00       Região Sudeste
6      Ricardo                45        512.00       Região Sudeste
7      Beatriz                25        587.00           Região Sul
8       Renato                40         10.00      Região Nordeste
9     Patricia                28        234.00  Região Centro-Oeste