# Séries Temporais em DataFrames

In [3]:
# Gerando dados Temporais
import pandas as pd
num_dias =  10
datas = pd.date_range(start='1/1/2025', periods= num_dias)
print(datas)
# Variavel datas recebe um range de datas que inicia em 1/1/2025 e tem 50 dias de duração
# start: data inicial
# periods: chama a variavel datas com o número de dias que queremos(num_dias = 50)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

# Usando estrutura criada para gerar indice em outro DataFrame

In [ ]:
df = pd.DataFrame(range(num_dias), columns=['numeros'], index=datas)
df
# Fazendo um DataFrame com a variavel datas como index e uma coluna numeros que recebe o range de 0 a 9

            numeros
2025-01-01        0
2025-01-02        1
2025-01-03        2
2025-01-04        3
2025-01-05        4
2025-01-06        5
2025-01-07        6
2025-01-08        7
2025-01-09        8
2025-01-10        9

# Tipos de dados do indice

In [5]:
# Acessando o item 8 no dataframe
df.index[8]

Timestamp('2025-01-09 00:00:00')

# Funções para extrair informações

In [6]:
# Acessando o dia do item 8 no dataframe
df.index[9].day

10

In [ ]:
# Acessando o mês do item 8 no dataframe
df.index[9].month

1

In [ ]:
# Acessando o ano do item 8 no dataframe
df.index[9].year

2025

# Filtrando indices de Séries Temporais

In [ ]:
# Acessando o dataframe onde o dia é igual a 
df[df.index.day == 8]

            numeros
2025-01-08        7

In [ ]:
# Acessando o dataframe onde o ano é 2025
df[df.index.year == 2025]

            numeros
2025-01-01        0
2025-01-02        1
2025-01-03        2
2025-01-04        3
2025-01-05        4
2025-01-06        5
2025-01-07        6
2025-01-08        7
2025-01-09        8
2025-01-10        9